version: "3"
services:
  db:
    container_name: db
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    volumes:
      - ./docker/:/docker-entrypoint-initdb.d/
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_data: {}
