version: 2.1
jobs:
  build_server:
    docker:
      - image: nixos/nix:2.3
    steps:
      - checkout
      - run:
          name: "Build"
          command: nix-build --pure release.nix
      - run:
          name: "HLint"
          command: nix-shell --run "hlint src && hlint app"
  build_dashboard:
    docker:
      - image: circleci/node:12.18
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "./dashboard/package.json" }}
      - run:
          name: "Install dependencies"
          command: cd dashboard && yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "./dashboard/package.json" }}
          paths:
            - ./dashboard/node_modules
      - run:
          name: "Build"
          command: cd dashboard && yarn run prod
      - run:
          name: "Lint"
          command: cd dashboard && yarn run lint
      - run:
          name: "Format"
          command: cd dashboard && yarn run fmt

workflows:
  version: 2
  build_all:
    jobs:
      - build_server
      - build_dashboard
