name: hakatime

on:
  release:
    types: [published]

jobs:
  cancel-running-workflows:
    runs-on: ubuntu-20.04
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  setup-amd64-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.docker-tags.outputs.tags }}
      labels: ${{ steps.docker-tags.outputs.labels }}
      json: ${{ steps.docker-tags.outputs.json }}
    steps:
      - uses: actions/checkout@v2
      - name: Docker tags
        id: docker-tags
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/mujx/hakatime
          tags: |
            type=semver,pattern={{version}}

  push-amd64:
    runs-on: ubuntu-latest
    needs:
    - setup-amd64-tags
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: mujx
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker build and push
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          push: true
          context: ./
          tags: ${{ needs.setup-amd64-tags.outputs.tags }}
          labels: ${{ needs.setup-amd64-tags.outputs.labels }}
